changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - feat!
        - fix!
        - feat(*)!
        - fix(*)!
    - title: Exciting New Features 🎉
      labels:
        - feat
    - title: Fixes 🔧
      labels:
        - fix
    - title: Other Changes
      labels:
        - '*'
