name: release-please
on:
  push:
    branches:
      - feature/ci
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: maven
          default-branch: feature/ci
          token: ${{ secrets.GITHUB_TOKEN }}
