name: Build release

on:
  push:
    branches: 
      - v2-develop

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.version.outputs.pe-version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get version
      id: version
      run: echo "pe-version=$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

    - name: Print version
      run: echo ${{ steps.version.outputs.pe-version }}

  create-tag:
    needs: get-version
    runs-on: ubuntu-latest
    outputs: 
      tag-already-exists: ${{ steps.checkTag.outputs.exists }}
    steps:
      - uses: actions/checkout@v3
      - uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with: 
          tag: "${{ needs.get-version.outputs.release-version }}"

      - run: echo ${{ steps.checkTag.outputs.exists }}

      - uses: rickstaa/action-create-tag@v1
        id: "createTag"
        if: ${{ steps.checkTag.outputs.exists }} == false
        with:
          tag: "${{ needs.get-version.outputs.release-version }}"

      - if: ${{ steps.checkTag.outputs.exists }} == true
        name: "Nothing to tag/release"
        run: echo "Nothing to tag/release, the tag ${{ needs.get-version.outputs.release-version }} already exists"

  release: 
    needs: create-tag
    runs-on: ubuntu-latest
    if: ${{ ! needs.create-tag.outputs.tag-already-exists }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Test
      run: cat Release.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
