name: Build release

on:
  push:
    branches: 
      - v2-develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: softprops/action-gh-release@v1
        with:
          name: Release plop
          tag_name: 3.4.5
          target_commitish: ${{ github.head_ref || github.ref }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
